[package]
name = "pattern-making"
version = "0.1.0"
authors = ["sm921 <seimei.221.921@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "src/pmrender",
    "src/pmmath",
    "src/pmdraw",
    "src/pmake",
]

[dependencies]
pmrender = {path = "src/pmrender"}
pmmath = {path = "src/pmmath"}
pmdraw = {path = "src/pmdraw"}