[package]
name = "pmrender"
version = "0.1.0"
authors = ["sm921 <seimei.221.921@gmail.com>"]
edition = "2018"

[dependencies]
vulkano = "0.23.0"
winit = "0.24"
vulkano-shaders = "0.23.0"
vulkano-win = "0.23.0"