[package]
name = "clothes"
version = "0.1.0"
authors = ["sm921 <seimei.221.921@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
wasm-bindgen = "*"
pmdraw = {path = "../pmdraw"}